#!/bin/bash

echo "
___  ____ _  _ ____    _ _  _ ____ ___ ____ _    _    ____ ____
  /  |___ |  | [__     | |\ | [__   |  |__| |    |    |___ |__/
 /__ |___ |__| ___]    | | \| ___]  |  |  | |___ |___ |___ |  \

"

#This is a script to help install docker and docker-compose files for the Raspberry pi

######################################################################

#Functions List

noanswer () { echo "Skipping..." ; }
update () { yes | sudo pacman -Syy; }
upgrade () { yes | sudo pacman -Syu; }
######################################################################

#
#System Update
#

echo "Would you like to update the system (Recommended)? (y/n/e)"
echo " "
echo "y=yes | n=no | e=exit-installer."
echo " "

read yesorno

if [ "$yesorno" = y ]; then
	update
	upgrade
	echo " "
	echo "Update Successful."
	echo " "
elif [ "$yesorno" = n ]; then
	echo "Skipping..."
	echo " "
else
	echo "Not a valid answer. Exiting..."
	exit 1
fi



#
#Docker Script Install
#

echo "Would you like to install Docker (Required)? (y/n/e)"

read yesorno

if [ "$yesorno" = y ]; then
	yes | sudo pacman -S docker
	sudo systemctl start docker.service
	sudo systemctl enable docker.service
	sudo groupadd docker
	sudo usermod -aG docker $USER
	newgrp docker
	sudo chown root:docker /var/run/docker.sock
	echo " "
	echo "Completed."
	echo " "
elif [ "$yesorno" = n ]; then
	echo "Skipping..."
	echo " "
else
	echo "Not a valid answer. Exiting..."
	exit 1
fi


echo "Installer Complete. Goodbye!"
