#!/bin/bash

echo "
___  ____ _  _ ____    _ _  _ ____ ___ ____ _    _    ____ ____
  /  |___ |  | [__     | |\ | [__   |  |__| |    |    |___ |__/
 /__ |___ |__| ___]    | | \| ___]  |  |  | |___ |___ |___ |  \

"

#This is a script to help install docker and docker-compose files for the Raspberry pi

######################################################################

#Functions List

noanswer () { echo "Skipping..." ; }
update () { yes | sudo pacman -Syy; }
upgrade () { yes | sudo pacman -Syu; }
######################################################################

#
#System Update
#

echo "Would you like to update the system (Recommended)? (y/n/e)"
echo " "
echo "y=yes | n=no | e=exit-installer."
echo " "

read yesorno

if [ "$yesorno" = y ]; then
	update
	upgrade
	echo " "
	echo "Update Successful."
	echo " "
elif [ "$yesorno" = n ]; then
	echo "Skipping..."
	echo " "
else
	echo "Not a valid answer. Exiting..."
	exit 1
fi



#
#Docker Script Install
#

echo "Would you like to install Docker (Required)? (y/n/e)"

read yesorno

if [ "$yesorno" = y ]; then
	yes | sudo pacman -S docker
	sudo systemctl start docker.service
	sudo systemctl enable docker.service
	sudo groupadd docker
	sudo usermod -aG docker $USER
	newgrp docker
	sudo chown root:docker /var/run/docker.sock
	echo " "
	echo "Completed."
	echo " "
elif [ "$yesorno" = n ]; then
	echo "Skipping..."
	echo " "
else
	echo "Not a valid answer. Exiting..."
	exit 1
fi



#test container

echo "Would you like to install radarr (Required)? (y/n/e)"

read yesorno

if [ "$yesorno" = y ]; then
	docker run -d \
  --name=radarr \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -p 7878:7878 \
  -v /path/to/data:/config \
  -v /path/to/movies:/movies `#optional` \
  -v /path/to/downloadclient-downloads:/downloads `#optional` \
  --restart unless-stopped \
  lscr.io/linuxserver/radarr
	echo " "
	echo "Completed."
	echo " "
elif [ "$yesorno" = n ]; then
	echo "Skipping..."
	echo " "
else
	echo "Not a valid answer. Exiting..."
	exit 1
fi

#test2
#test container

echo "Would you like to install test2 (Required)? (y/n/e)"

read yesorno

if [ "$yesorno" = y ]; then
	docker run -d \
  -p 8000:8000 -p 9000:9000 \
  --name portainer \
  --restart=always \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v portainer_data:/data \
  cr.portainer.io/portainer/portainer-ce:latest
	echo " "
	echo "Completed."
	echo " "
elif [ "$yesorno" = n ]; then
	echo "Skipping..."
	echo " "
else
	echo "Not a valid answer. Exiting..."
	exit 1
fi


echo "Installer Complete. Goodbye!"
